### ISSUE TITLE
US 28 - Criar Tela Inicial do Coordenador

### ISSUE THREAD

**Issue by thiagocmoreira** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#16]
# US 28 - Criar Tela Inicial do Coordenador
---
### Descrição:
Eu como coordenador, desejo visualizar uma tela inicial com as principais informações para usufruir de todos os recursos da aplicação.

### Critérios de aceitação
- A tela inicial deve exibir formulários e fóruns disponíveis para o coordenador;
- Em cada formulário/ fórum exibido ao coordenador, haverá um botão que poderá levar para uma nova tela;
- A seleção da opção "Ver detalhes" leva a visualização detalhada do item correspondente.

### Tarefas
- [x] Criar método para selecionar o próximo Fórum
- [x] Refatorar a ForumsPage e a ForumDetailPage para se adequarem a esse escopo
- [x] Levar a visualização detalhada do Fórum correspondente ao clicar em "Ver Detalhes"

**Comment by vitorbertulucci** [comment]
Lembrando... Colocar tasks e não esquecer dessa dívida técnica!!
