### ISSUE TITLE
US 09 - Informar Presença

### ISSUE THREAD

**Issue by Hargre** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#24]
# US 09 - Informar Presença
---
### Descrição:
Eu, como **coordenador**, desejo **informar presença** para **contribuir com levantamento de dados de comparecimento nos fóruns**.

### Critérios de aceitação
- A informação de presença deve ser salva ao se clicar o respectivo botão na página de fórum.
- Deve haver apenas um botão para confirmação de presença
- O botão deve mudar seu comportamento para cancelar presença caso o usuário tenha a presença confirmada
- O número de usuários que confirmaram presença deve ser mantido.
- Ao se cancelar a presença, a informação deve ser removida dos mecanismos de persistência (banco local/API).

### Tarefas
- [x] Trocar os botões presentes por apenas um botão de confirmação @Hargre  
- [x] Trocar visual do botão para quando tiver presença confirmada @Hargre  
- [x] Criar método de confirmação @DaniloBarros
- [x] Criar método cancelamento da confirmação @DaniloBarros
- [x] Trocar comportamento do botão para quando tiver presença confirmada @Hargre

**Comment by vitorbertulucci** [comment]
Cadastrar as tasks!
