### ISSUE TITLE
US 20 - Integrar API com sistema

### ISSUE THREAD

**Issue by Hargre** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#25]
# US 20 - Integrar API com sistema
---
### Descrição:
Eu como **desenvolvedor** desejo **integrar a API com o sistema** para **conseguir persistir o bancos de dados de maneira remota.**

### Critérios de aceitação
- O sistema deve ler e gravar dados no servidor.
- O sistema deve apresentar erros quando não conseguir se conectar ao servidor.

### Tarefas
- [ ] Arrumar nuget para requisições @DaniloBarros  
- [ ] Criar classe helper para API @Hargre 
- [ ] Criar método para apresentar erro ao falhar conexão com o servidor @DaniloBarros
- [ ] Fazer parser do JSON @Hargre 
- [ ] Atualizar funcionalidades para se comunicar com a API @DaniloBarros

**Comment by vitorbertulucci** [comment]
Cadastrem as tasks pra poder definir melhor a queima de pontos!
