### ISSUE TITLE
US26 - Pergunta Discursiva

### ISSUE THREAD

**Issue by lucaslrt** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#44]
# US 26 - Pergunta Discursiva
---
### Descrição:
Eu, como **administrador**, desejo **criar uma pergunta discursiva**, para **montar um formulário**.

### Critérios de aceitação
- [x] A pergunta discursiva deve ter um título
- [x] A pergunta não pode ser vazia ou em branco

### Tarefas
- [x] Testes
- [x] Criação de uma pergunta discursiva com título
- [x] Envio dela para o formulário

**Comment by DaniloBarros** [comment]
Criar critérios de aceitação e tasks @thiagocmoreira @vitorfhc
