### ISSUE TITLE
US24 - Pergunta Múltipla Escolha

### ISSUE THREAD

**Issue by lucaslrt** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#45]
# US 24 - Pergunta Múltipla Escolha
---
### Descrição:
Eu, como **administrador**, desejo **criar uma pergunta múltipla escolha**, para **montar um formulário**.

### Critérios de aceitação
- É possível criar múltiplas opções de resposta para a pergunta.
- Existe configuração para se permitir que mais de uma opção seja marcada.
- Existe configuração para se permitir que apenas uma opção seja marcada.
- A pergunta criada deve ser persistida em banco de dados.

### Tarefas
- [x] Criar view.
- [x] Criar método para adicionar nova opção de resposta.
- [x] Integrar com a API.

**Comment by DaniloBarros** [comment]
Criar critérios de aceitação e tasks @Hargre @arthur0496
