### ISSUE TITLE
US 34 - Refatorar View de Coordenador

### ISSUE THREAD

**Issue by lucaslrt** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#47]
# US 34 - Refatorar View de Coordenador
---
### Descrição:
Eu, como **desenvolvedor**, desejo **refatorar a view de coordenador**, para **melhorar sua usabilidade**.
### Critérios de aceitação
- [ ] A funcionalidade deve exibir X campos
- [ ] A funcionalidade deve ter um boneco rosa na tela 
- [ ] A funcionalidade deve responder em menos de 0.0042 ms

### Tarefas
- [ ] Tarefa 1 @Fulano

**Comment by DaniloBarros** [comment]
Criar tasks e tarefas @clarissalimab @vitorbertulucci @DaniloBarros

**Comment by lucaslrt** [comment]
Falta criar os critérios de aceitação e definir as tasks.
