### ISSUE TITLE
US 35 - Testes de Aceitação

### ISSUE THREAD

**Issue by lucaslrt** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#50]
US 35 - Testes de Aceitação
---
### Descrição:
Eu, como **desenvolvedor**, desejo **realizar testes de aceitação**, para **garantir que o aplicativo esteja com todas as funcionalidades corretas**.

### Critérios de aceitação
- [x] A aplicação deverá possuir os arquivos necessários para a realização dos testes
- [x] A aplicação deverá conter um teste de aceitação realizado e funcionando
- [x] A aplicação deverá conter testes como exemplos para serem seguidos pelos outros usuários

### Tarefas
- [x] Tarefa 1 - Achar uma ferramenta que consiga realizar tais testes.
- [x] Tarefa 2 - Testar a ferramenta.
- [x] Tarefa 3 - Aplicar os testes na solução.

**Comment by DaniloBarros** [comment]
Colocar critérios de aceitação e tarefas @RomeuCarvalhoAntunes @breno-mariz

**Comment by DaniloBarros** [comment]
Critérios de aceitação @RomeuCarvalhoAntunes @breno-mariz
