### ISSUE TITLE
US 36 - Controle de permissão

### ISSUE THREAD

**Issue by lucaslrt** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#51]
# US 36 - Controle de permissão
---
### Descrição:
Eu, como **desenvolvedor**, desejo **controlar a permissão de usuário**, para **que o mesmo possa utilizar de suas funcionalidades exclusivamente**.

### Critérios de aceitação
- [ ] O Sistema deverá ser capaz de identificar o tipo de usuário.
- [ ] O Sistema deverá restringir as funcionalidades de acordo com a permissão.
### Tarefas
- [ ] Tarefa 1 - Identificar se o usuário é um coordenador ou um administrador.
- [ ] Tarefa 2 - Carregar o app com a permissão de usuário correta.

**Comment by DaniloBarros** [comment]
Colocar critérios de aceitação e tarefas @RomeuCarvalhoAntunes @breno-mariz

**Comment by DaniloBarros** [comment]
Tenta colocar quais são as restrições que um usuário coordenador pode ter. 
As diferenças nas telas. 
Ex: Tela de visualização de Forum. Administrador possui a opção de editar/deletar Forum, Coodenador apenas visualizar dados
