### ISSUE TITLE
US 37 - Validar Campos

### ISSUE THREAD

**Issue by lucaslrt** [fga-gpp-mds/2017.1-Forum-Coordenadores-DEG#53]
# US 37 - Validar Campos
---
### Descrição:
Eu como **desenvolvedor**, desejo **acrescentar a validação de campos para os dados**, para **que os mesmos estejam de acordo com o desejado**.

### Critérios de aceitação
- [x] A funcionalidade deve exibir uma mensagem de erro;
- [x] A funcionalidade deve indicar o campo a ser corrigido pelo usuário.
- [x] Os campos de email Deve conter um '@', alguma string após seguido de um '.' e outra string
- [x] Os campos de senha devem possuir no mínimo um caractere maiúsculo, um minúsculo e um número, e o tamanho da senha deve possuir um mínimo de 9 caracteres.
- [x] Os campos de matrícula devem possuir um número exato de 9 caracteres.

### Tarefas
- [x] Validar campo de email no cadastro de usuário;
- [x] Validar campo de matrícula no cadastro de usuário;
- [x] Validar campo de senha no cadastro de usuário.

**Comment by DaniloBarros** [comment]
Tenta colocar nos critérios quais são as validações pros campos
